### ISSUE TITLE
Add VS Code documentation

### ISSUE THREAD

**Issue by georgia-at-pieces** [pieces-app/documentation#109]
VS Code

- [x] Suggested materials
- [x] Explored materials
- [x]  Related materials
- [x]  Connect account
- [ ]  Updating
- [x]  Troubleshooting common install problems
- [x]  Uninstalling
- [x]  Settings

**Comment by jordan-pieces** [comment]
@georgia-at-pieces would you like me to do the settings and Updating here?

**Comment by jordan-pieces** [comment]
This is done for now - we can add updating + screenshots here once we have some more components created in figma
