### ISSUE TITLE
feature request: Pieces should have an easy 'multiplayer' option

### ISSUE THREAD

**Issue by twilwa** [pieces-app/documentation#116]
Something like a button in OS that generates a link, then a setting in the desktop app/extensions to input an optional external OS? Ideally, a web-based lite client analog for the Desktop version that searches the db in my local OS that I can just share a link to. Optionally, a link that can be clicked/generated to export all my snippets to someone else's OS (and they can do the same) so teams can easily collaborate.

I'm not sure, but I might already have everything I need to build this myself, if my snippets are stored in OS and OS has a RESTful endpoint to query. Haven't tried something like that before but imagine it would be figureoutable, lol. I'll leave the feature request here anyway in case the team wants to pick it up and officially integrate said features.

**Comment by jordan-pieces** [comment]
Hey @twilwa thats a great idea, and we have had conversations around ideas similar to this in the past. We are looking to integrate more features like this in the coming releases from locations like the Copilot chat and from snippets themselves, so you will likely see this very soon! I will add this to our internal list as well to give the team an idea of what you are thinking. :) 

Thanks for sharing your ideas here as they are always welcome and we appreciate your interactions as a power user

**Comment by twilwa** [comment]
If the team is open to it, consider creating a bounty board! Have some developer friends I can think of that would find designing a feature like this an interesting one to sink their teeth into -- of course, it might necessitate sharing proprietary data, so perhaps not as feasible for closed-source projects, but a partially-open or sdk-based model might be worth thinking about. Appreciate the team being active on your issues board, always nice to have a line open to the dev team of useful software :)

**Comment by jordan-pieces** [comment]
@twilwa love this idea - let me save this for next week and we can facilitate some more conversation around this. :) ill see whats possible and not considering open vs closed source and any proprietary issues. At the very least we can try to setup a feature suggestion location where ideas can be presented at minimum. But I will get back to you! 

Thanks again so much and we will stay in touch. Im going to close this issue for now but I will reconnect with you next week.
