### ISSUE TITLE
Offline Details and Capabilities 

### ISSUE THREAD

**Issue by jwafu** [pieces-app/documentation#133]
We need to add a new page to the highlights and benefits sections to talk about the offline capabilities that are available throughout pieces and the expected results of different actions.

**Comment by davidmerwin** [comment]
If you need any extra help, feel free to contact me. I'm still learning, but I'll do my best. - David

**Comment by jordan-pieces** [comment]
@davidmerwin absolutely! would love to have some assistance here :) 

Let me know how i can help you get up and running with this repo on your device so you can open up a PR - and the best way to test and get the different features true functionality when not connected to the internet, is to turn off your wifi and test different base features that are available in the Pieces Desktop Application. we can focus on this app first and create a page called "Offline Capabilities" to hold all of the information that you find out. 

Here are some good steps to follow: 

- [ ] fork, and pull down the documentation repo
- [ ] test Pieces while wifi is turned off and see what the outcome is for different core features and capabilities
- [ ] write out these differences when offline and document in markdown format 
- [ ] open up a PR to preview your new page that you just created 

let me know how all of this sounds and how i can help ! I will add you to the assignees on this issue here

**Comment by jordan-pieces** [comment]
hey @davidmerwin was curious if you still had interest in testing these features and writing about your offline usage ? let me know and am more than happy to connect 👍

**Comment by jordan-pieces** [comment]
hey @davidmerwin just wanted to check in and see how you are doing with this "offline testing" - very curious to see how it turns out! 💯

**Comment by davidmerwin** [comment]
I have a goal to have final draft complete in about a week. What is the best way to send it to you for review? 
@jordan-pieces

**Comment by jordan-pieces** [comment]
@davidmerwin when you are ready to share you can send it over in a google doc if you would like, or if you have another preference let me know and we can work together on a good medium 👍

**Comment by davidmerwin** [comment]
I can understand that, you're right, a google doc is an excellent way for this Pieces project @jordan-pieces . 
Is there a way for direct texts on GitHub? I can send you my contact information and the rough draft. Looking forward to this!

-David @davidmerwin

**Comment by davidmerwin** [comment]
> I have a goal to have final draft complete in about a week. What is the best way to send it to you for review? @jordan-pieces

@jordan-pieces I have a rough draft I can send now; let me know the best way to share the Google doc. Based on your guidance, I can also start working on the repo RD V2. I think this is my first GitHub team project; thank you so much, Jordan, for your guidance (I have been on GitHub for a while, but I just recently made a career shift from Immigration/Refugee resettlement into programming languages. Starting postbac CS in Jan.)

**Comment by jordan-pieces** [comment]
@davidmerwin feel free to just comment your doc here - and you can share access to me --> jordan@pieces.app

Im glad that we could work together on this project and I'm excited to see your findings. Let me know how else you would like to be involved and if you want we can work together on some projects in [open source](https://github.com/pieces-app/opensource) as well we would love to have some more assistance and I am more than willing to spend some time working with you on any projects. 👍 will leave any comments in the doc and we can stay in touch here too!

**Comment by davidmerwin** [comment]
@jordan-pieces just sent you V1 RD google doc and word doc. Thank you for these opportunity's. Of course you're always welcome to assign me to any future Pieces collabs, . Looking forward to seeing your feedback and improvements,and I'm excited to continue collaboration sessions with you Jordan!

**Comment by davidmerwin** [comment]
> @davidmerwin when you are ready to share you can send it over in a google doc if you would like, or if you have another preference let me know and we can work together on a good medium 👍 looking forward to reading it!

Roger solid copy @jordan-pieces

**Comment by davidmerwin** [comment]
> @davidmerwin feel free to just comment your doc here - and you can share access to me --> [jordan@pieces.app](mailto:jordan@pieces.app)
> 
> Im glad that we could work together on this project and I'm excited to see your findings. Let me know how else you would like to be involved and if you want we can work together on some projects in [open source](https://github.com/pieces-app/opensource) as well we would love to have some more assistance and I am more than willing to spend some time working with you on any projects. 👍 will leave any comments in the doc and we can stay in touch here too!

@jordan-pieces the link below is the same doc to post on this repo, giving whoever clicks commenter access. I emailed you both V1 and V2 RDs in which you have editor access in that email link. V1 is a word doc, V2 RD is a google doc. https://docs.google.com/document/d/1MscMWDDEGE4j9ugU1f6EnLiTodYSzdOPVnpQNXypQuk/edit?usp=sharing

**Comment by jordan-pieces** [comment]
@davidmerwin just to update you, have already starting going through this document, and am pulling out some of the big sections that have some really great information in them in a more condensed way so it can be easy to read and understand some of the offline capabilities that you have shown through your research. will have some more information soon on this and know that it is still on the list of documents to review 👍

**Comment by CBID2** [comment]
How's this going @jwafu?

**Comment by mason-at-pieces** [comment]
@CBID2 as far as this goes, I think getting a page for this written up would be amazing.

Seems like this got put on hold but would love to start it back up.

If you want to work on this, that'd be great. Either can wait until I merge in the migration next week or just fork off of my Docusaurus branch.

**Comment by CBID2** [comment]
> @CBID2 as far as this goes, I think getting a page for this written up would be amazing.
> 
> Seems like this got put on hold but would love to start it back up.
> 
> If you want to work on this, that'd be great. Either can wait until I merge in the migration next week or just fork off of my Docusaurus branch.

Ok let's do it! :)

**Comment by mason-at-pieces** [comment]
@CBID2 Yeah actually idk if it can be done easily. Let's just wait until I merge it into main and then we'll get everything back up and running as far as contributions go 👍
