### ISSUE TITLE
Make the plugin buttons more clickable - similar to email 

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/documentation#143]
<img width="624" alt="Screenshot 2023-09-13 at 11 40 03 AM" src="https://github.com/pieces-app/documentation/assets/55861512/4066c062-39c0-48fb-86dd-3a776c62e986">

**Comment by chottuthejimmy** [comment]
I think I can get this done @jordan-pieces

**Comment by jordan-pieces** [comment]
@chottuthejimmy thank you so much for letting me know :) hope you are well!!
