### ISSUE TITLE
Change to installation 

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/documentation#144]
<img width="206" alt="Screenshot 2023-09-13 at 11 40 32 AM" src="https://github.com/pieces-app/documentation/assets/55861512/adc26f71-9bb1-4fb7-851a-1adae1974f9e">

Update title of section

**Comment by Sophyia7** [comment]
@jordan-pieces I want to take this up. If it's still open

**Comment by jordan-pieces** [comment]
@Sophyia7 absolutely feel free to tackle any of these, just make sure to mark me as a reviewer and open up a PR! Currently the previewing system is not working on the docs.page platform so you will be coding without a preview available, let me know if you have any questions
