### ISSUE TITLE
Updated Apps and Plugins section

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/documentation#146]
- [ ] remove the desktop app from the top of this list 

<img width="199" alt="Screenshot 2023-09-13 at 11 48 34 AM" src="https://github.com/pieces-app/documentation/assets/55861512/2d0b422f-f9d7-4ce0-8d56-000aacbf6e29">

**Comment by Sophyia7** [comment]
@jordan-pieces For this issue, Should I delete the **Pieces Desktop App** or set the **Pieces Desktop App** to the bottom?

**Comment by jordan-pieces** [comment]
closing this for now - going to remove this as we dont want to update it right now
