### ISSUE TITLE
'What am I installing' page image is not clear enough

### ISSUE THREAD

**Issue by caleb-at-pieces** [pieces-app/documentation#156]
The first image displayed on 'what am I installing' does not really convey much to the user in terms of what they are installing:

We could add a diagram in order to show the relation ship of the plugins, pieces os, and the desktop app, or simply remove it all together.

<img width="796" alt="image" src="https://github.com/pieces-app/documentation/assets/133268200/19cb9953-6ea7-4fc8-a470-dc67cf6b785c">

**Comment by jordan-pieces** [comment]
@laurin-at-pieces do we have a good graphic that we could use as a header here?
