### ISSUE TITLE
Incorrect shortcut keys

### ISSUE THREAD

**Issue by caleb-at-pieces** [pieces-app/documentation#158]
A table of shortcut keys has the Mac CMD key written in the Windows column. Obsidian plugin page

**Comment by jordan-pieces** [comment]
@caleb-at-pieces can you drop the link to this? i was not able to find this and didnt see it corrected in the PR just merged, can fix this today

**Comment by jordan-pieces** [comment]
okay just let me know and i can get anything updated - also i may have just missed it but can you share the doc with all of the review info from MJ?
