### ISSUE TITLE
Favicon dark mode

### ISSUE THREAD

**Issue by caleb-at-pieces** [pieces-app/documentation#159]
The favicon of https://pieces.app/ needs to be updated, it is near impossible to see in dark mode.

**Comment by jordan-pieces** [comment]
Current State for me:

## DM:

![Screenshot 2023-11-13 at 2 02 43 PM](https://github.com/pieces-app/documentation/assets/55861512/dd18c1a8-707a-4a09-9382-606ac2e8c39a)

## LM: 

![Screenshot 2023-11-13 at 2 03 12 PM](https://github.com/pieces-app/documentation/assets/55861512/6e56bc58-cd5b-42ee-bca3-d0de64921a48)

I don't think that i can do anything to adjust the favicon dynamically here - so we may be out of luck if it can be responsive right now. Also if this is in reference to the actual home site we can forward this in website channel and reopen if it is true, let me know @caleb-at-pieces but i am closing this for now
