### ISSUE TITLE
Request: API Specifications for Pieces OS

### ISSUE THREAD

**Issue by Pratere** [pieces-app/documentation#177]
Hello, I have browsed the open source repositories and the docs at docs.pieces.app but have not been able to find any api specifications for Pieces OS. The Client repo's components provide insight into the available endpoints, but is there any plans to release something like OpenAPI specifications? 

This would be useful for creating projects in languages other than typescript that are able to interact with the API.

Thanks!

**Comment by Pratere** [comment]
Thanks @jordan-pieces! I am in the Discord and will keep an eye out. And yes I hope to contribute over in example-ts!

**Comment by jordan-pieces** [comment]
@Pratere i am going to go ahead and close this since we are in contact via discord and also the `example-ts` repo :)
