### ISSUE TITLE
Support Different Emails Across Cloud Services

### ISSUE THREAD

**Issue by tsavo-at-pieces** [pieces-app/documentation#18]
Per [Internal Support Ticket](https://discord.com/channels/1098986658851999776/1102138306965291018/1102575067612856350)

We will soon need to build a bridging functionality to enable users to have different emails across cloud providers i.e. GitHub & GMail so that services are automatically connected.

**Comment by jordan-pieces** [comment]
@tsavo-at-pieces im going to close this for now
