### ISSUE TITLE
Add new gifs and images instead of discord CDN images that are there now

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/documentation#184]
Follow up for the remote pieces OS instance; 1 final step to update all of the images on the remote connection documentation page. 😄

**Comment by jordan-pieces** [comment]
@mason-at-pieces just want to bump this so it doesnt get lost this week - should be pretty easy and we can get this closed up!

**Comment by mason-at-pieces** [comment]
@jordan-pieces Yep, messaged Laurin about this earlier in the morning and she is working on those. Should have them updated today 👍
