### ISSUE TITLE
Too much RAM usage.

### ISSUE THREAD

**Issue by H-SamurAI** [pieces-app/documentation#186]
The RAM usage is not Normal even when i doing nothing just the app in the windows tray.

![image](https://github.com/pieces-app/documentation/assets/46361691/9affc2e6-65bf-4966-baad-17dec5f4b5b4)

**Comment by mason-at-pieces** [comment]
Hey @H-SamurAI! Pieces OS does tend to run somewhat high on memory usage while using a Local LLM on our Copilot but it should not be idling above 1GB.

Could you send your Pieces OS version?

An option you could try, if you haven't already, is click the Pieces OS icon in your Windows toolbar, and then click the "Optimize Memory Usage" button. This should clean up some of the memory that is being used.

**Comment by H-SamurAI** [comment]
[cid:e3cd526c-a0c9-47d7-a3ac-ba0838a01dae]
and yes of course I've tried Optimize Memory Usage option and it's indeed reducing the usage by around 50% or more but I think this is still not reasonable for an idle app and I think this optimize thing should be automatically not manually.

And to let u know I like this app and I think it will be a great development tool in the future and all I want by this to make it better.
________________________________

**Comment by mason-at-pieces** [comment]
@H-SamurAI For the Pieces OS version, it should display the number in this format (vX.X.X) in the toolbar menu.

As for the high memory usage in idle, we are actively reducing this number and recently pushed updates to get this number under 1GB but it does seem that it has increased again.

We have other updates like offloading Local LLM's that you've downloaded which will free up more space.

However, more generally, this is where all of the data that we process goes through and thus is going to have above-average memory usage but we will continue to look into more ways to reduce this.

**Comment by H-SamurAI** [comment]
Here is the version.
![image](https://github.com/pieces-app/documentation/assets/46361691/397c7c1f-ddde-4a65-97b2-e269130296a8)

**Comment by H-SamurAI** [comment]
Here is the version.
![image](https://github.com/pieces-app/documentation/assets/46361691/c1381f3d-fc30-4f72-9d5d-772d0e45be4c)

**Comment by mason-at-pieces** [comment]
@H-SamurAI Ok, you are on the latest version. I will relay this conversation to our team to see what possibilities there are around optimizing memory.

Do you have any thoughts about what you would think is acceptable memory usage for idling?

**Comment by mason-at-pieces** [comment]
> IDK really but i think it would be ~ 50 MB.

Ok, to be completely honest, I'm not sure if that is achievable since this is where all of our on-device, ML processing takes place however we will continuously try to optimize this 👍
