### ISSUE TITLE
Cloud sync

### ISSUE THREAD

**Issue by devnull69** [pieces-app/documentation#191]
I'm missing a feature which is very (vitally) important for me to keep using Pieces

I should be able to sync my pieces to a cloud service somehow so that when I install Pieces on different machines and login with the same account I will see the same pieces automatically

This seems to me as a very basic feature, so I was surprised that it's obviously not there.... or maybe I just wasn't able to find it?

**Comment by mason-at-pieces** [comment]
Hey @devnull69 👋

This feature is absolutely a high priority for us. We are currently building out the infrastructure for it and plan to have this feature released in early Q1 2024!

**Comment by jordan-pieces** [comment]
planning on closing this later this evening @mason-at-pieces @devnull69
