### ISSUE TITLE
Import GitHub Gists not adding anything

### ISSUE THREAD

**Issue by abstractindia** [pieces-app/documentation#192]
All my Gists are discovered.
When I select all and click on Add (save), it says adding 22 snippets.
All snippets are getting green tick mark in the bottom right corner.
But in desktop nothing is imported.

**Comment by mason-at-pieces** [comment]
Hey @abstractindia! So you are seeing the green checkmarks on the snippets as you save them but they are not appearing in your snippet list when you go back to the List or Gallery View?

**Comment by abstractindia** [comment]
Yes! exactly.

**Comment by mason-at-pieces** [comment]
Hey @abstractindia! Thank you for your patience.

If you could send over the version of your Pieces OS and Desktop app, that could help us find a possible reason for your issues.

Here is a quick explanation on finding your Desktop App version: [https://docs.pieces.app/features/user-settings#information](https://docs.pieces.app/features/user-settings#information)

**Comment by abstractindia** [comment]
Pieces OS is 7.0.1 and Pieces for Developer is 2.8.3.

**Comment by mason-at-pieces** [comment]
Hey @abstractindia! Is it possible for you to send over a screen recording that shows you going through this process?

We are not able to reproduce this but a video would help us solve this for you.

**Comment by abstractindia** [comment]
Hi @mason-at-pieces. Yesterday, I tried it again and once after the green check mark in bottom, I hit the "Start Over" icon with circular arrow and all the gist got saved in my list view. I don't know if that was required step but I got what I wanted. So for now this issue can be closed.

**Comment by mason-at-pieces** [comment]
> Hi @mason-at-pieces. Yesterday, I tried it again and once after the green check mark in bottom, I hit the "Start Over" icon with circular arrow and all the gist got saved in my list view. I don't know if that was required step but I got what I wanted. So for now this issue can be closed.

Ok, that's wonderful to hear! Enjoy your weekend and please reach out if anything else comes up!
