### ISSUE TITLE
Add instructions for giving permissions for Firefox plugin in the docs

### ISSUE THREAD

**Issue by shivay-at-pieces** [pieces-app/documentation#198]
Add instructions on how to add permissions for Firefox plugin in Mozilla Firefox in the docs.

**Comment by shivay-at-pieces** [comment]
+ Reorder the Firefox plugin to below Edge plugin to have all browser based plugins together.

**Comment by jordan-pieces** [comment]
@shivay-at-pieces i updated this as well to lead with IDE's > webext > text editors (roughly) let me know if we should update this any further:

![image](https://github.com/pieces-app/documentation/assets/55861512/51daf104-790e-46cb-9606-6a14de5711c4)

**Comment by shivay-at-pieces** [comment]
Looks good.

**Comment by jordan-pieces** [comment]
https://docs.pieces.app/~211/extensions-plugins/firefox @shivay-at-pieces if you have a second to double check my work here
