### ISSUE TITLE
Change intro paragraph on https://docs.pieces.app/extensions-plugins/chrome

### ISSUE THREAD

**Issue by cole-pieces** [pieces-app/documentation#210]
Change "Using the Pieces Chrome Extension with the Pieces Desktop App makes saving code easy from anywhere you interact with code on the web."

to: "Save, share, and ask questions about code you find online without leaving your current tab by using our Chromium extensions. **Note**: If you're using Opera or Brave browsers, you are in the right place. Please follow the steps below to install Pieces in your browser, whether you use Chrome, Opera, or Brave."

**Comment by jordan-pieces** [comment]
Updated
