### ISSUE TITLE
Add Icons to Each Plugins Landing Page 

### ISSUE THREAD

**Issue by jwafu** [pieces-app/documentation#213]
Would love to get plugin images on all of the landing pages! Should all be included in the project currently. 

### Steps: 

- [ ] Create custom component for the icon itself 
- [ ] add the new component to each page with the proper icon from the `/docs/assets` directory

## Update each page 
- [ ] chrome
- [ ] vscode
- [ ] edge
- [ ] jetbrains
- [ ] obsidian
- [ ] jupyterlab
- [ ] teams
- [ ] firefox
- [ ] azure

**Comment by RohanMishra315** [comment]
Hey @jordan-pieces just for confirmation , the code should written  be here right!
![Screenshot 2023-12-17 111304](https://github.com/pieces-app/documentation/assets/121561397/63520ead-0077-479f-8b2e-462b4d471762)

**Comment by jordan-pieces** [comment]
@RohanMishra315 i will have some more details soon for you about this - i may need to take care of this initial issue with the icons and in the future **i can be sure to use a more specific tag** for issues that may be stronger candidates for getting started in this space as there is a lot of nuance in the docs.page system and how we can reference these icon files from a component. 

I hope thats alright with you and i **can let you know once we have some more issues prepared on this specific repo** 👍

**Comment by RohanMishra315** [comment]
That's alright  @jordan-pieces

**Comment by Stroller15** [comment]
hi @jordan-pieces, can you please assign this issue to me I can help out with this

**Comment by jordan-pieces** [comment]
@RohanMishra315 apologies for assigning this issue to someone else - as I have still not had time to get this taken care of and can now use some assistance. 👍 I'm going to assign @Stroller15 this issue to start working while you finish up [this issue on the example-ts project](https://github.com/pieces-app/example-ts/issues/59).

@Stroller15 let me know if you need any guidance with adding the components inside of the docs.page framework,
there is some documentation on adding components and this framework [here](https://use.docs.page/components/custom).

Also a great idea to open up a PR when you first create your branch that way it creates a generated preview that you can view - it will show up in the comments of the PR itself. you can see an example of that [here](https://github.com/pieces-app/documentation/pull/235#issuecomment-1888017758).

Most, if not all of the assets you will need will be inside of the `/assets/*` directory and each plugin page should have an icon next to the h1 header text that appears in `/extensions-plugins` directory. 💯

**Comment by RohanMishra315** [comment]
that's alright! @jordan-pieces .Hey @Stroller15  you need some assistance let me know, it'll  be my pleasure to help you!

**Comment by Stroller15** [comment]
sure @RohanMishra315, I'll let you know If I stuck somewhere

**Comment by Stroller15** [comment]
@RohanMishra315 can we connect on discord regarding some issue I have

**Comment by RohanMishra315** [comment]
Yeah sure! vengence02 is the username.

**Comment by jordan-pieces** [comment]
@Stroller15 if you are having issues and need assistance, it would be great if you would have those conversations here, as it can be beneficial for others when they have questions or are wondering about how some of this system works. 

👍 @RohanMishra315 continue being a huge help to others it is very helpful for the team here and for the members of the community 🥇

**Comment by Stroller15** [comment]
> @Stroller15 if you are having issues and need assistance, it would be great if you would have those conversations here, as it can be beneficial for others when they have questions or are wondering about how some of this system works.
> 
> 👍 @RohanMishra315 continue being a huge help to others it is very helpful for the team here and for the members of the community 🥇

sure @jordan-pieces, I will start conversation here from now

**Comment by RohanMishra315** [comment]
Yeah, It'll be helpful to do required conversations here.

**Comment by Stroller15** [comment]
hey @jordan-pieces why local preview is not working?

**Comment by jordan-pieces** [comment]
@Stroller15 there is something broken on the docs.page side of things - there is an issue around this here: https://github.com/invertase/docs.page/issues/262 that has been sitting for a little bit, but the team over there is super busy currently

**Comment by jordan-pieces** [comment]
@Stroller15 when you open up that PR, your PR # that is attached to it, can be used in the URL that is the preview branch, wanted to drop an example here just in case: `https://docs.pieces.app/~248/installation-getting-started/pieces-os`

You can use that pattern as a guide for yourself if the PR is not attached to the comments

**Comment by CBID2** [comment]
How's this coming along @jordan-pieces?

**Comment by jordan-pieces** [comment]
@CBID2 I have not heard any updates here - want to check in with @Stroller15 and @RohanMishra315 on the status here?

**Comment by CBID2** [comment]
> @CBID2 I have not heard any updates here - want to check in with @Stroller15 and @RohanMishra315 on the status here?

If they don't respond, can I work on this issue @jordan-pieces?

**Comment by jordan-pieces** [comment]
@CBID2 absolutely, lets just give this a day or two more to see if any responses come in, but would love to get this taken care of 💯

**Comment by jordan-pieces** [comment]
alright @CBID2 if you want to get started on this one that would be great 👍  if theres anything you need let me know, and the preview should show up when you open your PR now that i have added this: https://github.com/pieces-app/documentation/blob/main/.github/workflows/preview-link.yml

**Comment by RohanMishra315** [comment]
Yeah @CBID2 go on with these issue,I think @Stroller15 may be busy with something,anyway if you need assistance we are here!

**Comment by CBID2** [comment]
> Yeah @CBID2 go on with these issue,I think @Stroller15 may be busy with something,anyway if you need assistance we are here!

Hi @RohanMishra315. I created a draft PR for this. Can you check to see if I'm on the right track?

**Comment by CBID2** [comment]
Hey @jwafu. @mason-at-pieces is solving this issue with PR #275, so I closed mine. You can assign it to them instead.

**Comment by mason-at-pieces** [comment]
@CBID2 are we good to close this issue as well?

Also, Jordan isn't on our team anymore so you can just ping me for anything 👍

**Comment by CBID2** [comment]
> @CBID2 are we good to close this issue as well?
> 
> Also, Jordan isn't on our team anymore so you can just ping me for anything 👍

Oh thanks for clarifying @mason-at-pieces. Sure you can close it
