### ISSUE TITLE
Investigate if we can detect versions without user input

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#216]
As a user, when I land on the support landing page, the version of POS/PFD/other plugins should be automatically detected and presented to me. 

If I am behind on version, the page will suggest that I update. 

This may solve issues that the user is experiencing and will overall reduce support tickets.

**Comment by jordan-pieces** [comment]
since we have the ability to utilize iFrames ( based on this here #254 ) we should be able to achieve this no problem. 👍
