### ISSUE TITLE
Create Landing Page Copy

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#217]
https://docs.google.com/document/d/1hapn6NY-jnqsta-CsamEXqin8Axe4HEgBWyiqDOcNFQ/edit?usp=sharing

**Comment by jordan-pieces** [comment]
this should already be completed in terms of the documentation site, is there more needed here from either @rosie-at-pieces or @cole-pieces ?

**Comment by rosie-at-pieces** [comment]
done! we can close this
