### ISSUE TITLE
Enable downloads on Pieces OS page

### ISSUE THREAD

**Issue by cole-pieces** [pieces-app/documentation#224]
At the very top of the Pieces OS page (https://docs.pieces.app/installation-getting-started/pieces-os) we should offer download buttons in a tabbed format so users can download Pieces OS from this page. 

Also, to be more clear on the macOS, windows and linux download pages that POS is different than PFD, we should add "Desktop Application" after "Pieces for Developers" in each dropdown about alternative installation options
<img width="725" alt="Screenshot 2024-01-08 at 3 56 32 PM" src="https://github.com/pieces-app/documentation/assets/129767962/1a2f2d76-85cd-4e18-a701-e8913fbdd9ce">

**Comment by mason-at-pieces** [comment]
@cole-pieces We already have the tabbed install buttons further down in the `Installation` section on the Pieces OS page. Do we want to keep that and also put it at the top or just move it to the top?

**Comment by mason-at-pieces** [comment]
@cole-pieces Here's the preview link for these changes. I have not changed the Pieces OS page yet

https://docs.pieces.app/~232

**Comment by cole-pieces** [comment]
@mason-at-pieces yeah we should move the tabbed section to the top of the Pieces OS page - and at present these tabs just have buttons to the download page. Can we provide the actual links to download Pieces OS here? Without the links to the desktop app?

**Comment by mason-at-pieces** [comment]
@cole-pieces Missed this, doing it now

**Comment by jordan-pieces** [comment]
@mason-at-pieces @cole-pieces what is the status here?

**Comment by cole-pieces** [comment]
I don’t see any edits yet https://docs.pieces.app/installation-getting-started/pieces-os


Cole Stark

Chief Marketing Officer
***@***.***

**Comment by jordan-pieces** [comment]
Reopening as we do not have the tabs added to the top of the Pieces OS page
