### ISSUE TITLE
Redirect old support page to new one

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#228]
Anyone who lands on https://code.pieces.app/support should be directed to https://docs.pieces.app/support

**Comment by jordan-pieces** [comment]
this now has been setup - to be sure feel free to test the code.pieces.app/support route - we did in office and the redirect is working well for us but let me know how its functioning from your perspective

**Comment by rosie-at-pieces** [comment]
works well for me! 

when i search "pieces for developers support" that one still comes up (although it does redirect properly). anyway we can promote the actual page to be the first hit?

![Screenshot 2024-01-11 at 5 55 30 PM](https://github.com/pieces-app/documentation/assets/152189388/f0685b35-27d1-498c-9272-f8679bd2835a)

**Comment by jordan-pieces** [comment]
i think this is a matter of SEO - but i believe that over time the new page will start to inherit the SEO of its old page. i dont have a huge amount of knowledge on that front so maybe @cole-pieces can shed some more light on how that could work out

**Comment by rosie-at-pieces** [comment]
no worries - i'm happy with the redirect so you can close, we can talk SEO separately

**Comment by cole-pieces** [comment]
@rosie-at-pieces it will resolve itself over time, there's nothing we can do
