### ISSUE TITLE
update onboarding drip campaign to include new links

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#230]
https://docs.google.com/document/d/1fKMulYzr_kcuIuZMJuFLk0mDhChMFyR-fN4W1tLfJxo/edit?usp=sharing

**Comment by jordan-pieces** [comment]
this has been updated and is g2g - i did this while in customer.io today

**Comment by cole-pieces** [comment]
@jordan-pieces thanks for doing that!
