### ISSUE TITLE
support repo: add link to Discussions in Issues templates

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#236]
![Screenshot 2024-01-11 at 5 57 22 PM](https://github.com/pieces-app/documentation/assets/152189388/1adc19a8-de0f-4f03-a981-b35c3ff9c551)

see example above https://github.com/microsoft/vscode/issues/new/choose. copy should be:

Feature or Enhancement Request
Post your idea in discussions for the Pieces team and community to discuss!

**Comment by rosie-at-pieces** [comment]
https://github.com/microsoft/vscode/blob/main/.github/ISSUE_TEMPLATE/config.yml

**Comment by jordan-pieces** [comment]
@rosie-at-pieces is this related to support and issues on the support repo?

**Comment by jordan-pieces** [comment]
This should be handled via that PR that adds this copy and link to discussions in the template @rosie-at-pieces
