### ISSUE TITLE
Backup and Restore: Details for Linux and Windows needed

### ISSUE THREAD

**Issue by HRA42** [pieces-app/documentation#239]
Link to the article: https://docs.pieces.app/features/back-up-and-restore

I think this article needs separation for windows and Linux, as currently only macOS is shown, specially we need the correct path and more details about the backup that is created on start up?

**Comment by jordan-pieces** [comment]
@HRA42 this is a great observation and we can start to scope out the different resources and materials that we will need to get together. We can use this issue to track some of the updates as they are made, but first lets identify the key differences and make sure we get the screenshots created as well - @mason-at-pieces can also assist here. 

Lets get a list started here and get going on this this week

**Comment by jordan-pieces** [comment]
@HRA42 just wanted to keep you in the loop and let you know we got the paths updated here - if you are looking for more information let me know 👍 i can reopen the issue if we are in need of additional information or assistance.

**Comment by HRA42** [comment]
Hey @jwafu and @mason-at-pieces 

Quick suggestion on this:

On documentations like this I think from a UX perspective it would be better to use env variables (like %username% on Windows)

I think the overhauled docs looks beautiful now. Thank you :)

**Comment by mason-at-pieces** [comment]
> On documentations like this I think from a UX perspective it would be better to use env variables (like %username% on Windows)

I like that a lot and will add those changes to our new docs under the `docusaurus` branch.

> I think the overhauled docs looks beautiful now. Thank you :)

Thank you! We hope to get the migration to Docusaurus complete within the next week 👍
