### ISSUE TITLE
Copilot Updates Throughout the Copilot Pages

### ISSUE THREAD

**Issue by jwafu** [pieces-app/documentation#242]
We have a number of updates that we should get taken care of, but generally should take a pass and get any updates here. If we have other .gifs of improvements that can be made.

- [x] add new screenshots from laurin
- [ ] Get a header graphic for the copilot added
- [ ] any gifs around copilot runtimes 
- [ ] more internal links to the page 
- [ ] add information about copilot features 
- [ ] double check for all of the appropriate features are on both the copilot pages for the plugin copilot and the desktop copilot
- [ ] add links to other pages throughout the docs site that includes information around the copilot and link to the appropriate sections

**Comment by shivay-at-pieces** [comment]
We should add a CTA about our open source initiatives around Copilot in the end, if folks are interested in building their own Copilot, probably in the plugin copilot doc.

**Comment by mason-at-pieces** [comment]
@shivay-at-pieces I just added the new gifs from laurin to the copilot page on my migration branch. I feel like this is good to close and we can come back to this.

Thoughts?
