### ISSUE TITLE
Update Help and Support links on docs

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#249]
Anywhere there is "help and support" at the bottom of the page (mostly in the plugins docs) please update the title to 

"Support and Community"

and have the options be:

Get Support - link to https://docs.pieces.app/support
Join our Discord - link to https://discord.gg/getpieces

<img width="1615" alt="Screenshot 2024-01-31 at 11 48 50 AM" src="https://github.com/pieces-app/documentation/assets/152189388/68377d00-e83e-4f8a-acc8-a0c80a5d619a">
<img width="315" alt="Screenshot 2024-01-31 at 11 49 26 AM" src="https://github.com/pieces-app/documentation/assets/152189388/95dad18a-0707-47ff-b766-423d042597bd">

**Comment by CBID2** [comment]
I can do it @rosie-at-pieces. I’m new here! :)

**Comment by jordan-pieces** [comment]
@CBID2 let me know if you need any additional support in getting this done, to offer some guidance here. In the example of the Pieces Chrome Extension is what the update process would look like: 

1. First clone and fork the [Documentation Repo](https://docs.pieces.app)
2. Inside of the repo, locate the file `/docs/extensions-plugins/chrome.mdx`

> Important note: [Docs.page](https://use.docs.page) framework uses the headers on the page to build the sidebar list that is circled up above. So to update the Help & Support link and header, check out step number 3 that follows.

3. Navigate down to the heading: 

```markdown 
## Help & Support

- [Contact Us](https://code.pieces.app/contact)
- [Feedback & Bug Support](https://getpieces.typeform.com/to/mCjBSIjF#page=docs-chrome)
- [Join our Discord](https://discord.com/invite/getpieces)
```

4. Update the header to: ` ## Support and Community`
5. Update the bullet points and your final result should look like: 

``` markdown 
## Support and Community

- [Get Support](https://docs.pieces.app/support)
- [Join our Discord](https://discord.gg/getpieces)
```

Then this change would need to be replicated across all of the pages listed under `/extensions-plugins/*`.

Checklist of Plugin Pages that need Updated:
- [ ] `/azuredatastudio.mdx`
- [ ] `/chrome.mdx`
- [ ] `/edge.mdx`
- [ ] `/firefox.mdx`
- [ ] `/jetbrains.mdx`
- [ ] `/jupyterlab.mdx`
- [ ] `/obsidian.mdx`
- [ ] `/teams.mdx`
- [ ] `/vscode.mdx`


@CBID2 Let me know if you have any questions, and to see the preview of a PR just make sure that the PR is open on the documentation repo and you will see it in the comments. The local previews DO NOT work based on the documentation on docs.page so just use this preview style: 

![Screenshot 2024-02-05 at 2 24 50 PM](https://github.com/pieces-app/documentation/assets/55861512/96c66053-01a5-4556-bcc7-25ab6123c8fc)

You can see an example of this here in a recent [PR](https://github.com/pieces-app/documentation/pull/254#issuecomment-1927855539).
