### ISSUE TITLE
Migrate gif's to the new ones with rounded corners Plugin Copilot

### ISSUE THREAD

**Issue by caleb-at-pieces** [pieces-app/documentation#250]
Laurin went ahead and rounded the corners on many of the gif's that were on the plugin copilot page, we need to ensure that we are now correctly using the ones with the rounded corners

SETTING COPILOT CONTEXT: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/COPILOT_CONTEXT_GENERIC/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-COPILOT_CONTEXT_GENERIC-MACOS-16X9-1_31_2024.GIF

SETTING COPILOT RUNTIME: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/COPILOT/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-COPILOT-MACOS-16X9-1_31_2024.GIF.gif

OCR: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/COPILOT_OCR/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-COPILOT_OCR-MACOS-16X9-1_31_2024.GIF.gif

DIRECTIVES: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/ANY_FEATURE/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-DIRECTIVES-MACOS-16X9-1_31_2024.GIF.gif

SLASH COMMANDS: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/COPILOT/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-SLASH_COMMANDS-MACOS-16X9-1_31_2024.GIF.gif

PERSISTED CHATS: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/COPILOT/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-PERSISTED_CHATS-MACOS-16X9-1_31_2024.GIF.gif

SUGGESTED MATERIALS: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/SUGGESTED_MATERIALS/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-SUGGESTED_MATERIALS-MACOS-16X9-1_31_2024.GIF.gif

RELATED FILES: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/COPILOT_CONTEXT_FILES/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-RELATED_FILES-MACOS-16X9-1_31_2024.GIF.gif

RIGHT CLICK SAVE: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/RIGHT-CLICK_SAVE/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-RIGHT-CLICK_SAVE-MACOS-16X9-1_31_2024.GIF.gif

RIGHT CLICK CONTEXT: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/CONTEXTUAL_COPILOT/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-RIGHT_CLICK_SET_CONTEXT-MACOS-16X9-1_31_2023.GIF.gif

CONTEXT ENRICHMENT: https://storage.googleapis.com/pieces_multimedia/PROMOTIONAL/PIECES_FOR_DEVELOPERS/VS_CODE/MACOS/CONTEXT_ENRICHMENT/16X9/PIECES_FOR_DEVELOPERS-VS_CODE-CONTEXT_ENRICHMENT-MACOS-16X9-1_31_2024.GIF.gif

**Comment by mason-at-pieces** [comment]
@caleb-at-pieces "Right-Click Context" is not on the docs, can you create an issue for that so we can add it and add it to the `Cleanup and SDK Docs` Milestone.

I've added all the others for #275
