### ISSUE TITLE
Add New FAQs

### ISSUE THREAD

**Issue by CBID2** [pieces-app/documentation#256]
## Description
Pieces' docs site is currently going through a major migration, so the FAQ sections needed to be updated

**Comment by rosie-at-pieces** [comment]
@CBID2 we actually do have an FAQ section [here](https://docs.pieces.app/faq), however it is sorely out of date! We will be addressing that very soon.

**Comment by CBID2** [comment]
> @CBID2 we actually do have an FAQ section [here](https://docs.pieces.app/faq), however it is sorely out of date! We will be addressing that very soon. 

Oh thanks @rosie-at-pieces! :) I'll be glad to help you update it. I'm already done updating the support links

**Comment by mason-at-pieces** [comment]
@CBID2 for this issue, if we want to switch it to updating our FAQ page, I think that would be perfect.

@rosie-at-pieces you may have some sort of list of faqs that we need to add/update as well. You can just post them here 👍

**Comment by CBID2** [comment]
> @CBID2 for this issue, if we want to switch it to updating our FAQ page, I think that would be perfect.
> 
> @rosie-at-pieces you may have some sort of list of faqs that we need to add/update as well. You can just post them here 👍

Made the change @mason-at-pieces. I'd love to work on this issue once @rosie-at-pieces posts the list.

**Comment by rosie-at-pieces** [comment]
<img width="329" alt="Screenshot 2024-03-12 at 5 10 25 PM" src="https://github.com/pieces-app/documentation/assets/152189388/9e0f92f2-6101-4482-9c3a-f47e01b4f119">

**Comment by rosie-at-pieces** [comment]
These are ready to be published! Please see the google doc.

**Comment by rosie-at-pieces** [comment]
<img width="1254" alt="Screenshot 2024-03-15 at 12 13 48 PM" src="https://github.com/pieces-app/documentation/assets/152189388/3a9fd7cc-8a3f-4d77-9e9b-47d9ea3eea97">
<img width="220" alt="Screenshot 2024-03-13 at 11 41 03 AM" src="https://github.com/pieces-app/documentation/assets/152189388/a0
<img width="870" alt="Screenshot
<img width="859" alt="Screenshot 2024-03-13 at 11 01 23 AM" src="https://github.com/pieces-app/documentation/assets/152189388/2c4789d7-6155-44c4-8792-4c989066be8a">
 2024-03-13 at 11 24 46 AM" src="https://github.com/pieces-app/documentation/assets/15218
<img width="362" alt="Screenshot 2024-03-13 at 11 04 00 AM" src="https://github.com/pieces-app/documentation/assets/152189388/8d1e9534-5348-459b-b2ad-08024d582e95">

<img width="395" alt="Screenshot 202
<img width="1099" alt="Screenshot 2024-03-13 at 11 08 56 AM" src="https://github.com/pieces-app/documentation/as
<img width="236" alt="Screenshot 202
<img width="390" alt="Screenshot 2024-03-13 at 9 12 17 AM" src="https://github.com/pieces-app/documentation/assets/152189388/a7f3926b-af0d-4cd8-b69e-94c41aafcb3d">
4-03-13 at 10 59 30 AM" src="https://github.com/pieces-app/documentation/assets/152189388/c647feb4-6efb-490d-84f0-53f12ac4170e">
sets/152189388/7e4c4294-55fc-409a-a4bd-3cb53ad5b2f6">
4-03-13 at 11 24 00 AM" src="https://github.com/pieces-app/documentation/assets/152189388/23be0de3-1f71-4f0b-8782-00a5d21fb5ee">
9388/476f0e89-72b2-45a2-a02
<img width="303" alt="Screenshot 2024-03-13 at 11 00 25 AM" src="https://github.com/pieces-app/documentation/assets/152189388/8d285a2b-fa37-4159-815b-18cae51ba3f0">
f-05f8694cd909">
6e7c36-8f7b-4dab-8f9c-75261209c748">

**Comment by CBID2** [comment]
Hey @mason-at-pieces! :) I'm currently reviewing [docusaurus' documentation for tab components](https://docusaurus.io/docs/markdown-features/tabs#displaying-a-default-tab). It suggests to have a theme folder so they can be imported, I can't find it in Pieces' docs repository. Can you point it out to me please?

**Comment by mason-at-pieces** [comment]
Hey @CBID2, there should be examples of how to use Tabs in the repository already. I've used them a few times so you might be able to find them by searching.

**Comment by rosie-at-pieces** [comment]
@CBID2 i just updated one section here - "Local Model Crashing"

Here is the image for it:
<img width="1254" alt="Screenshot 2024-03-18 at 5 28 18 PM" src="https://github.com/pieces-app/documentation/assets/152189388/101f46e3-cc9b-4bf8-a948-0a2efa7de017">
