### ISSUE TITLE
Pieces plugin in Android Studio runs at startup anyway!

### ISSUE THREAD

**Issue by H-SamurAI** [pieces-app/documentation#258]
I've disabled the plugin from opening at startup of android studio.

![image](https://github.com/pieces-app/documentation/assets/46361691/01a95ce5-0cea-40cf-994d-50b74d99ebb2)

but still opening at every time!

![image](https://github.com/pieces-app/documentation/assets/46361691/9f37dd03-bf2c-4906-ad5e-d036b48aeb98)

**Comment by mason-at-pieces** [comment]
Hey @H-SamurAI, sorry you ran into this issue. Could you create a new issue on our GitHub Support Repo so that we can get you the help you need?

https://github.com/pieces-app/support/issues

**Comment by H-SamurAI** [comment]
Done.
Should i close this issue now?
