### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by abstractindia** [pieces-app/documentation#259]
Suggesting some features for future.
(1) Add a shortcut "Open Pieces Desktop" in the Pieces OS tray right click menu.
(2) An expandable menu (Accordion Menu) in list view in Pieces Desktop based on language. Please refer to the image.

![Image_2024-02-08_10-06-55-M](https://github.com/pieces-app/documentation/assets/14857472/7c0c7186-70ea-4a9e-ba51-1764d161c971)

**Comment by rosie-at-pieces** [comment]
@abstractindia this is awesome feedback! we would love to see feedback like this in our [Discussions](https://github.com/pieces-app/support/discussions) board under the "Ideas" section so we can better track it.
