### ISSUE TITLE
Wrong URL Naming on "Sync Across Multiple Devices" section 

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/documentation#262]
I noticed the URL for Windows was C:/Users/user/Documents/com.pieces.os/production/Pieces instead of C:\Users\user\Documents\com.pieces.os\production\Pieces.

**Comment by mason-at-pieces** [comment]
@Sophyia7 Whenever you can, try to reproduce this. I tested it on my windows machine and it worked fine for me.

**Comment by Sophyia7** [comment]
@mason-at-pieces I tried both ways i.e, / and \ and it worked. Maybe I should delete this issue.

**Comment by mason-at-pieces** [comment]
@Sophyia7 Yes we can close this issue.
