### ISSUE TITLE
Update the "Connecting to a Remote Pieces OS Instance" Section

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/documentation#266]
When setting up or adjusting Pieces VS Code extension settings for WSL, it would be best if the Ngrok custom URL be added to the Remote WSL connection instead of the entire Vscode workspace so it doesn't break the Pieces connection account when the user isn't using WSL. Please take a look at the attached image for a visual. 

![image](https://github.com/pieces-app/documentation/assets/66218403/cef1966d-ba4e-416e-bac4-f12d6d861dc4)

**Comment by mason-at-pieces** [comment]
@Sophyia7 does this issue still apply with the latest changes on the Docusaurus branch?

**Comment by mason-at-pieces** [comment]
@Sophyia7 Is this still an ongoing issue?

**Comment by Sophyia7** [comment]
It's not. @mason-at-pieces
