### ISSUE TITLE
Migrate docs site to docusaurus

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#270]

**Comment by mason-at-pieces** [comment]
@rosie-at-pieces I linked the branch Im doing the migration on to this issue 👍

**Comment by mason-at-pieces** [comment]
Phase 1:
- [] Ensure redirects/rewrites are 302 and work

Phase 2:
- [ ] [Get search working](https://docusaurus.io/docs/search#using-algolia-docsearch)
- [ ] Add SDK Docs

**Comment by rosie-at-pieces** [comment]
https://docs.google.com/document/d/1kXSXK37I-i22LrBKcD-0G4NlIbx8sqOjVRoXLIbLAVg/edit?usp=sharing
