### ISSUE TITLE
Pieces Glossary

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#271]

**Comment by shivay-at-pieces** [comment]
cc @Arindam200 @shivay-at-pieces

**Comment by shivay-at-pieces** [comment]
Compare with KWDs list and identify the words which require individual pages: https://docs.google.com/spreadsheets/d/194u4694_xCOZtlOM34Qxmpgoez9Qmiq28BfmOyPD1BQ/edit#gid=202067699

**Comment by Arindam200** [comment]
Can you please assign me?

**Comment by shivay-at-pieces** [comment]
Update: PR being created for the glossary page. 

2. Initiate meeting with Mark for detailed pages, starting with Assests. = will also be used to update the SDK docs for updating description of the properties.
