### ISSUE TITLE
10 Typescript Boilerplate Code Snippets to keep handy

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#272]

**Comment by rosie-at-pieces** [comment]
https://docs.google.com/document/d/1LrW5MGJ7UIOpe1yuhk9jgGGyBLZbbJ6U76JKKLU5cpI/edit?usp=sharing

**Comment by mason-at-pieces** [comment]
@rosie-at-pieces Did we want to add these as a page on docs?

**Comment by rosie-at-pieces** [comment]
Feels like maybe should be part of a collection?

**Comment by mason-at-pieces** [comment]
So we actually do have a page for collections: https://docs.pieces.app/product-highlights-and-benefits/collections

but it's hidden atm

**Comment by mason-at-pieces** [comment]
Also here is really our "Collections" page: https://code.pieces.app/collections

**Comment by mason-at-pieces** [comment]
But I feel like this may be better as a larger issue around bringing collections from the code.pieces.app site over the docs?

**Comment by rosie-at-pieces** [comment]
maybe we bubble this up a bit and put it in "use" if we're keeping that structure

**Comment by mason-at-pieces** [comment]
Yep, funny enough this "Learn, Build, Use" structure is exactly how the new docs site will roll out.

1st Phase is learn, going out EoW
2nd Phase is build, SDK docs going out by EoQ
3rd Phase is use, which will be all new stuff essentially

**Comment by rosie-at-pieces** [comment]
no collection, just blog

**Comment by mason-at-pieces** [comment]
@rosie-at-pieces Are we good to close this issue then?

**Comment by rosie-at-pieces** [comment]
yep!
