### ISSUE TITLE
Update PiecesOS version requirements

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#291]
<img width="541" alt="Screenshot 2024-03-15 at 3 44 50 PM" src="https://github.com/pieces-app/documentation/assets/152189388/cb913e39-0836-48e9-b704-df7dfe13709c">

Jupyterlab, VS Code, and Teams all say the wrong PiecesOS version

**Comment by Sophyia7** [comment]
@mason-at-pieces I will work on this

**Comment by mason-at-pieces** [comment]
@rosie-at-pieces do you know the correct minimum version?

**Comment by rosie-at-pieces** [comment]
should be 8.0.0!
