### ISSUE TITLE
Beta User Docs Page

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#302]

**Comment by mason-at-pieces** [comment]
@cole-pieces @rosie-at-pieces Any idea what we want to put on this?

**Comment by rosie-at-pieces** [comment]
https://docs.google.com/document/d/1QEArynx0RCpBg0GCSC3NMkynSOcaKp8wrkL_F3mxU0M/edit?usp=sharing

**Comment by mason-at-pieces** [comment]
@rosie-at-pieces Let me know when that doc is finalized and I will get it on a preview link 👍 

Also, any idea on what we want the URL for this page to be?

**Comment by rosie-at-pieces** [comment]
docs.pieces.app/beta-user-group

**Comment by rosie-at-pieces** [comment]
it's almost done @mason-at-pieces so you can get started on that now
