### ISSUE TITLE
Revamp Community Page

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#317]
Just a redesign of the [community page](https://docs.pieces.app/community)

Will be converting h3's into cards and cleaning it up in general.

Also will be adding more youtube content, noted in this issue https://github.com/pieces-app/documentation/issues/314

**Comment by subhajit20** [comment]
Hey what do you mean by - `Will be converting h3's into cards and cleaning it up in general.` ? 
can you explain a bit

**Comment by shivay-at-pieces** [comment]
Add a section for all of our Twitter spaces that we have conducted @mason-at-pieces
