### ISSUE TITLE
Update "Back Up and Restore" Documentation

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#343]
https://docs.pieces.app/features/back-up-and-restore

Need to update with new information now that we have an official Back Up and Restore feature

**Comment by CBID2** [comment]
Hi @rosie-at-pieces! :) Can you specify the information that needs changing?

**Comment by mason-at-pieces** [comment]
Hey @CBID2, this is related to our new Backup and restore feature. So we will probably move this github version to another page and replace it with the official feature.

You can read about it here a bit: https://code.pieces.app/updates/backup-restore-context-view

**Comment by CBID2** [comment]
> Hey @CBID2, this is related to our new Backup and restore feature. So we will probably move this github version to another page and replace it with the official feature.
> 
> 
> 
> You can read about it here a bit: https://code.pieces.app/updates/backup-restore-context-view

Thanks @mason-at-pieces! :)
