### ISSUE TITLE
Add mention of Pieces Copilot features to JetBrains page

### ISSUE THREAD

**Issue by cole-pieces** [pieces-app/documentation#346]
https://docs.pieces.app/extensions-plugins/jetbrains doesn't have any info about "ask copilot" or other copilot features, only how to change your runtime. We should mention setting context and other things that are available.

**Comment by mason-at-pieces** [comment]
@laurin-at-pieces Do you know if we have gifs for `Ask Copilot` and other copilot features for jetbrains? Maybe this is on your list to get while doing this big update?

Here's the link to where the updates videos would go but we are currently using vs code videos but need Jetbrains: https://documentation-git-346-add-mention-c81e9b-pieces-for-developers.vercel.app/extensions-plugins/jetbrains#pieces-copilot

**Comment by laurin-at-pieces** [comment]
@mason-at-pieces Yes! This is on the list, i do not yet have updated jetbrains copilot gifs but they are next in line
