### ISSUE TITLE
Update Community Page with New Beta Form

### ISSUE THREAD

**Issue by cole-pieces** [pieces-app/documentation#364]
Update mentions of Beta Program to "Early Access Program" and change typeform to https://getpieces.typeform.com/earlyaccess

**Comment by mason-at-pieces** [comment]
@cole-pieces Let me know if this preview link hits on those: https://documentation-git-beta-program-updates-pieces-for-developers.vercel.app/early-access-program

We also have a pr still opened related to this page for some final touches from @rosie-at-pieces: https://github.com/pieces-app/documentation/pull/363

**Comment by cole-pieces** [comment]
oh @mason-at-pieces apologies for the miscommunication. You can leave the old typeform on this page as it is specific to the WPE EAP. I am talking about updating https://docs.pieces.app/community with the new typeform, since the new form is a broader EAP form that doesn't necessarily apply only to copilot testing and the other requirements we have for testing the WPE

**Comment by mason-at-pieces** [comment]
Ok, gotcha. Updated 👍
