### ISSUE TITLE
Broken links on https://docs.pieces.app/product-highlights-and-benefits/connecting-to-a-remote-pieces-os-instance

### ISSUE THREAD

**Issue by cole-pieces** [pieces-app/documentation#366]
Fix link on mention of "1 machine with the Pieces for Developers VS Code extension 404 installed" (404)
Remove link on  https://caleb.pieces.cloud  because it's broken (410)

**Comment by mason-at-pieces** [comment]
Fixed in https://github.com/pieces-app/documentation/pull/369
