### ISSUE TITLE
Remove link to http://localhost:1000 on all pages

### ISSUE THREAD

**Issue by cole-pieces** [pieces-app/documentation#368]
It's being rendered as a clickable URL on the docs and is a 404, so bad for SEO. Remove hyperlink on:

https://docs.pieces.app/build/reference/typescript/apis/ApplicationsApi
https://docs.pieces.app/build/reference/python/apis/ApplicationsApi
https://docs.pieces.app/build/reference/dart/apis/ApplicationsApi
https://docs.pieces.app/build/reference/kotlin/apis/ApplicationsApi
https://docs.pieces.app/build/reference/python/apis/AssetApi
https://docs.pieces.app/build/reference/kotlin/apis/ConversationApi
https://docs.pieces.app/build/reference/kotlin/apis/ModelApi
https://docs.pieces.app/build/reference/dart/apis/WellKnownApi
https://docs.pieces.app/build/reference/kotlin/apis/WellKnownApi
https://docs.pieces.app/build/reference/dart/apis/ConversationApi
https://docs.pieces.app/build/reference/typescript/apis/ConnectorApi
https://docs.pieces.app/build/reference/dart/apis/AssetApi
https://docs.pieces.app/build/reference/kotlin/apis/ModelsApi
https://docs.pieces.app/build/reference/typescript/apis/ModelsApi
https://docs.pieces.app/build/reference/python/apis/ConversationApi
https://docs.pieces.app/build/reference/dart/apis/ConnectorApi
https://docs.pieces.app/build/reference/kotlin/apis/ConversationsApi
https://docs.pieces.app/build/reference/dart/apis/ModelsApi
https://docs.pieces.app/build/reference/kotlin/apis/ConnectorApi
https://docs.pieces.app/build/reference/dart/apis/ConversationsApi
https://docs.pieces.app/build/reference/typescript/apis/ModelApi
https://docs.pieces.app/build/reference/python/apis/ModelsApi
https://docs.pieces.app/build/reference/python/apis/ModelApi
https://docs.pieces.app/build/reference/kotlin/apis/AssetApi
https://docs.pieces.app/build/reference/python/apis/ConnectorApi
https://docs.pieces.app/build/reference/typescript/apis/ConversationApi
https://docs.pieces.app/build/reference/python/apis/QGPTApi
https://docs.pieces.app/build/reference/kotlin/apis/AssetsApi
https://docs.pieces.app/build/reference/kotlin/apis/QGPTApi
https://docs.pieces.app/build/reference/typescript/apis/ConversationsApi
https://docs.pieces.app/build/reference/typescript/apis/AssetsApi
https://docs.pieces.app/build/reference/python/apis/ConversationsApi
https://docs.pieces.app/build/reference/typescript/apis/WellKnownApi
https://docs.pieces.app/build/reference/python/apis/AssetsApi
https://docs.pieces.app/build/reference/dart/apis/AssetsApi
https://docs.pieces.app/build/reference/typescript/apis/AssetApi
https://docs.pieces.app/build/reference/typescript/apis/QGPTApi
https://docs.pieces.app/build/reference/dart/apis/ModelApi
https://docs.pieces.app/build/reference/python/apis/WellKnownApi
https://docs.pieces.app/build/reference/dart/apis/QGPTApi

**Comment by mason-at-pieces** [comment]
Fixed in #369
