### ISSUE TITLE
Add Sidebar Link for Pieces Desktop App down load page that can live on the Docs

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/documentation#37]
This will require a new page being made, but it can be modeled after the old page that we had previously on webflow, with the added information that is present fir getting started on pages like: 

https://docs.pieces.app/extensions-plugins/teams 

- [x] Sidebar link added 
- [x] Install page created and copy edited 
- [x] Copy reviewed before publishing

**Comment by jordan-pieces** [comment]
@georgia-at-pieces this would be the best next thing actually for the docs if you wanted to start with this page

**Comment by jordan-pieces** [comment]
https://github.com/pieces-app/documentation/assets/55861512/1a0db801-9ad8-402f-b3e0-163aea397869

Heres the screen recording of the old page - if you get me an idea of all the copy and send it to me i can get it up on a PR so you can see it on a live link @georgia-at-pieces

**Comment by georgia-at-pieces** [comment]
@jordan-pieces Here's the copy! https://docs.google.com/document/d/1prnBB02QjnSipIhnCt8N8TaqeyIY06II9iK5j43Ozcc/edit#

**Comment by jordan-pieces** [comment]
So we are going to add this as the overview page and reworked the order of the sidebar, im going to tuck these changes into that PR

**Comment by jordan-pieces** [comment]
leaving out the install page update for now - will revisit

**Comment by jordan-pieces** [comment]
tested and link is working properly
