### ISSUE TITLE
Fix broken links on model pages in docs

### ISSUE THREAD

**Issue by cole-pieces** [pieces-app/documentation#370]
Remove hyperlink to http://localhost:8080/authentication/response on:
https://docs.pieces.app/build/reference/dart/models/SeededPKCE
https://docs.pieces.app/build/reference/kotlin/models/SeededPKCE
https://docs.pieces.app/build/reference/python/models/SeededPKCE

Remove hyperlink to:
https://auth.pieces.services/authorize
https://pieces.us.auth0.com/api/v2/

or any other auth link

wherever it's listed (mostly in "audience" and "domain" property names)

**Comment by mason-at-pieces** [comment]
Fixed in #369
