### ISSUE TITLE
Adding fix for "Hard Resetting" your copilot in the event a response freezes

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#371]
There's a few ways to do this:
1. Double-click the "Stop" button to the right of the Copilot Input
2. Open the Copilot Settings dialog and select "Hard Reset Active Runtime"
3. Open the Copilot LLM Runtime Config dialog and select "Hard Reset Active Runtime"

All of these should yield a response like so:
<img width="787" alt="Screenshot 2024-04-22 at 9 48 45 AM" src="https://github.com/pieces-app/documentation/assets/152189388/5993b2d5-3d5e-4282-aa98-4031ced873ce">

**Comment by rosie-at-pieces** [comment]
Lets start with just a docs section for it on the Copilot page, then list it in the FAQ, and we can create a short power-tip on the YouTube. Then once the YouTube video is up, we can repurpose the content for an in-app tip

**Comment by mason-at-pieces** [comment]
Added the following to the copilot and faq pages:

Copilot - https://documentation-git-371-adding-fix-f-1280cd-pieces-for-developers.vercel.app/features/pieces-copilot#resetting-the-copilot-runtime
FAQ - https://documentation-git-371-adding-fix-f-1280cd-pieces-for-developers.vercel.app/faq#resetting-the-copilot-runtime
