### ISSUE TITLE
Create page for WPE

### ISSUE THREAD

**Issue by cole-pieces** [pieces-app/documentation#378]
We need a page for the Workstream Pattern Engine (WPE), describing what the tech does, how to use it, how to resolve common issues, etc. There's some info on our beta plan we can leverage that talks about it a bit https://docs.google.com/document/d/1o58YcMkOW-Qq2aw1ZCwyFKGNOKkrTvrzCikZnJ_llbQ/edit#heading=h.dom6q0bjug62

**Comment by rosie-at-pieces** [comment]
take a look at [this](https://docs.google.com/document/d/1ehDo4RevhTdEIzS6QkP5Kl8ZfijMLDF1a1AUktiAcpQ/edit?usp=sharing), I used our EAP Docs page as a jumping off point and just pulled out all the EAP-specific stuff. 

left a few comments, could use some input!
