### ISSUE TITLE
Add more details to backup & restore and Sync across devices pages

### ISSUE THREAD

**Issue by cole-at-pieces** [pieces-app/documentation#383]
Need to add paragraph to both https://docs.pieces.app/features/back-up-and-restore and https://docs.pieces.app/product-highlights-and-benefits/sync-across-multiple-devices-using-github at the top, describing exactly what these processes mean, and describing when you'd want to do one instead of the other (along with internal links between both)

**Comment by mason-at-pieces** [comment]
Related issue: https://github.com/pieces-app/documentation/issues/343
