### ISSUE TITLE
Add documentation on saved materials action bar

### ISSUE THREAD

**Issue by cole-at-pieces** [pieces-app/documentation#396]
We can put content on https://docs.pieces.app/features/user-settings

![custom-toolbar](https://github.com/pieces-app/documentation/assets/129767962/e99448fb-201b-4650-86ff-575dbd832fc1)

**Comment by mason-at-pieces** [comment]
Has been added here: https://documentation-git-saved-materials-995075-pieces-for-developers.vercel.app/features/user-settings#saved-materials-action-toolbar
