### ISSUE TITLE
Add Tailscale as an alternative option to ngrok for remote connectivity to Pieces OS

### ISSUE THREAD

**Issue by shivay-at-pieces** [pieces-app/documentation#400]
In a recent conversation on Discord, a user asked a question whether the user can use Tailscale instead of ngrok for the remote URL setup while using Pieces OS. 

I have tested Tailscale and it works completely fine. So we can add it's reference in the documentation. We don't need to necessarily add complete walkthrough steps. But just a reference: that you can use Tailscale as well would be great. 

<img width="1262" alt="image" src="https://github.com/pieces-app/documentation/assets/143828586/9e04b163-a6ca-4fd0-92ff-8840d7ce15de">

**Comment by CBID2** [comment]
On it @shivay-at-pieces
