### ISSUE TITLE
Pieces OS automatically closes on using a Local LLM for chat

### ISSUE THREAD

**Issue by lakshits11** [pieces-app/documentation#401]
So i installed mistral 7b gpu . I have rtx 4050 6gb on my machine. Whne i ask a question, pieces os automatically closes. Please help.

**Comment by lakshits11** [comment]
I even set pieces os to run with nvidia gpu in my graphics settings. I have a Windows 11 laptop

**Comment by shivay-at-pieces** [comment]
Hey @lakshits11 do you mind creating an issue on https://github.com/pieces-app/support/issues to help you better with this issue?

**Comment by rosie-at-pieces** [comment]
closing as this needs to be posted in the support repo
