### ISSUE TITLE
Visual Studio Extension release documentation for 1.4.0

### ISSUE THREAD

**Issue by robert-at-pieces** [pieces-app/documentation#413]
This release:

- [x] CodeLens - Explain & Comment. Should also explain how to disable Pieces CodeLens.
- [x] Quick Action - Fix (red squiggles)
- [x] Asset explorer filtering by Tags or Language (classification)
- [x] Copilot ThemePicker to change message background color

Doc update requirements from previous:

- [x] Requires Pieces OS >= 9
- [x] How to Show Pieces Tool Windows if not present in the IDE.
- [x] Pieces Explorer feature should be added to docs.
    - [x] Asset Preview.
    - [x] Copy to Clipboard
    - [x] Insert at Cursor
    - [x] Modifying  (tags, links, content) or deleting assets
    - [x] How to change default action

**Comment by mason-at-pieces** [comment]
@robert-at-pieces Please check and review the changes here and let me know if they look good: https://documentation-git-product-docs-updates-pieces-for-developers.vercel.app/extensions-plugins/visual-studio

**Comment by mason-at-pieces** [comment]
@robert-at-pieces How do you edit the default action?
