### ISSUE TITLE
Copilot Release 1.1.0 Docs Tasks

### ISSUE THREAD

**Issue by caleb-at-pieces** [pieces-app/documentation#414]
- [x] theme picker
- [x] support for latex / math -> html parsing in the message generation

**Comment by shivay-at-pieces** [comment]
@mason-at-pieces we should add a gif for the theme selection

**Comment by caleb-at-pieces** [comment]
> @caleb-at-pieces Please check and review the end of the features list here for updates: https://documentation-git-product-docs-updates-pieces-for-developers.vercel.app/features/pieces-copilot#features

For of these instead of saying 'copilot can now...' it should just say 'copilot can do this' as this is docs, not some sort of release note

for the latex bit, it could always generate latex, we are just now rendering the latex in a nicer format instead of showing raw latex.

Theme Support should be Theme Customization

This feature allows a user to customize the look of their Copilot, and is integral to resolve the issue that sometimes the text in the copilot is unreadable.

**Comment by caleb-at-pieces** [comment]
> @mason-at-pieces we should add a gif for the theme selection

let's do gif's for both of them if possible

**Comment by mason-at-pieces** [comment]
@shivay-at-pieces @caleb-at-pieces Got the video shivay made for theme in 👍
