### ISSUE TITLE
Add a section in our Privacy/Security page specifically for the WPE

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/documentation#417]
1. LOCAL: user's clicking around desktop and the WPE is taking screenshots
2. LOCAL: WPE does it's magic and runs OCR on these screenshots
3. LOCAL: WPE data is stored on-device
4. User navs to the desktop copilot and has GPT 4 selected
5. CLOUD: Relevant data from the WPE is queried and sent to GPT 4
6. User changes model to Mistral
7. LOCAL: Relevant data from the WPE is queried and sent to Mistral

Gather real-time context without compromising data privacy, as all context is stored and processed on-device, with additional filtering for secrets, passwords, and other sensitive data.

**Comment by mack-at-pieces** [comment]
Updates:
- All WPE algorithms, processing, and storage occurs on device
- When a user asks a question for the copilot, and Live Context is ON, the copilot will query data that was aggregated from the WPE (on-device), and leverage content that it believes is relevant as context for the copilot. (feel free to mention RAG/link out to our existing RAG docs/page(s))
- Once the "relevant" content has been queried and assembled, it is leveraged as context for the copilot prompt and sent to the respective LLM
- If you are using a CLOUD LLM, this data will be sent to the CLOUD LLM
- If you are using a LOCAL LLM, this data will be sent to the LOCAL LLM and remain on-device
- Maybe add a callout, if you are concerned about privacy, we recommend using a Local LLM with the Pieces Copilot - Mistral, Phi-2, Llama2, etc.
- Results may vary depending on the selected LLM

**Comment by mason-at-pieces** [comment]
Preview link: https://documentation-git-wpe-eap-updates-pieces-for-developers.vercel.app/product-highlights-and-benefits/privacy-security-data#live-context

**Comment by rosie-at-pieces** [comment]
the "how live context works" and "real-time context gathering" seems redundant - am i missing a distinction between those?

**Comment by mason-at-pieces** [comment]
Yep agreed, have a new build without `real-time context gathering`

**Comment by mason-at-pieces** [comment]
here we go: https://documentation-git-wpe-eap-updates-pieces-for-developers.vercel.app/product-highlights-and-benefits/privacy-security-data#live-context
