### ISSUE TITLE
Quick "How To Video" for Joining EAP

### ISSUE THREAD

**Issue by tsavo-at-pieces** [pieces-app/documentation#427]
@laurin-at-pieces if you could do a quick video on joining EAP from within pieces settings that would be awesome 🙌 

Perhaps you could sign in with the hello@pieces.app/support@pieces.app/marketing@pieces.app email - @georgia-at-pieces has login details. 

Doesn't need a voice over - @landon-at-pieces  can throw some music on there. 

@mason-at-pieces can get that into the docs once it is up on YouTube. May need an Early Access Program Playlist on YT as well i.e. this can be where we release videos/demos that are initially available to EAP users.

**Comment by mason-at-pieces** [comment]
Also @laurin-at-pieces if we could get an image that shows the user profile picture with the EAP icon on it, that'd be great

**Comment by laurin-at-pieces** [comment]
@tsavo-at-pieces @mason-at-pieces here's an MP4 and an webm version for the docs site, let me know how this is looking

https://github.com/pieces-app/documentation/assets/117211369/b890c913-2613-498b-8883-8dd46e6b901d

[joining-early-access-program-small.webm](https://github.com/pieces-app/documentation/assets/117211369/d696541b-5f75-4234-b796-191bc3344088)

**Comment by laurin-at-pieces** [comment]
@mason-at-pieces here are two screenshots screenshot options

<img width="1156" alt="Screenshot 2024-05-20 at 1 29 22 PM" src="https://github.com/pieces-app/documentation/assets/117211369/562f9578-dfff-4ea8-bbab-4166c40e2c12">

<img width="1920" alt="Screenshot 2024-05-20 at 1 29 31 PM" src="https://github.com/pieces-app/documentation/assets/117211369/3d5efa01-93bb-4f5b-be5e-7daf945fac09">

**Comment by mason-at-pieces** [comment]
Perfect, got all that in @laurin-at-pieces

**Comment by mason-at-pieces** [comment]
@tsavo-at-pieces Ive added the video with no audio to the docs as I think that works better than have youtube embeds.

However we can still get @landon-at-pieces to add some music to it and upload that to youtube to start an `EAP` playlist

**Comment by landon-at-pieces** [comment]
This looks great. Happy to spice this up. Do we have a certain folder of music to remain uniform across branding? Or a subscription to an audio service?

**Comment by tsavo-at-pieces** [comment]
> This looks great. Happy to spice this up. Do we have a certain folder of music to remain uniform across branding? Or a subscription to an audio service? 

Not sure but anything probs works!

**Comment by landon-at-pieces** [comment]
Beauty. Slotted for 11 AM CT. Had to ensure we're good on any copyright issues w/ music.
