### ISSUE TITLE
Quick "How to Video - Enabling Workstream Pattern Engine Permissions on MacOS"

### ISSUE THREAD

**Issue by tsavo-at-pieces** [pieces-app/documentation#428]
Need a quick video on enabling WPE for MacOS from within the app. 

@mack-at-pieces maybe you can knock this one out with a quick screen record. Doesn't need any voice over or anything. Just want it for the documentation. 

@laurin-at-pieces if you end up knocking this out - you'll likely need to start on a fresh DB and ensure the permissions from before were disabled. 

@landon-at-pieces can get this up on YT once it is done and comment the link here on this issue. 

@mason-at-pieces can get this into the documentation at relevant locations from there!

**Comment by mack-at-pieces** [comment]
I can lead the charge on this one. 

- [ ] Enabling from Settings
- [ ] Enabling from Copilot

**Comment by mason-at-pieces** [comment]
Perfect @mack-at-pieces, if you just upload those videos as `mp4s` here, ill make sure they get everywhere they are needed on the docs

**Comment by mack-at-pieces** [comment]
@mason-at-pieces @laurin-at-pieces @landon-at-pieces @tsavo-at-pieces these may require a little editing - lmk if you'd like me to just edit it or share other form factors.

**This is enabling the WPE from Settings:**
MP4 - https://github.com/pieces-app/documentation/assets/30325757/619edb4e-a197-41fd-adfc-83576bd2fde5
Raw Screen Studio - https://drive.google.com/drive/folders/1bOO01oUZYSSAao3EpwjhgMPKaa_rbQ-W?usp=drive_link

Instructions:
- Navigate to settings either via the Power Menu or via the Settings popover
- Navigate to the Machine Learning tab in the Settings View
- Click the "power icon" to turn the Workstream Pattern Engine "on"
- Enable the permissions from top to bottom
- Wait for the Desktop App to refresh
- The permissions dialog will re-appear and refresh itself, which should automatically turn the WPE on if the permissions were granted successfully

**This is enabling the WPE after first message:**
MP4 - https://github.com/pieces-app/documentation/assets/30325757/acdc5ced-9395-42b3-9f03-578219591bf6
Raw Screen Studio - https://drive.google.com/drive/folders/1musBLyradRRsbfC7OSaUPzdcYQUa-zdR?usp=drive_link

> For Raw SS Folders: Just download the raw folder from Drive and de-compress it and it'll be the screenstudio file

Instructions:
- Navigate to the Copilot and create a new chat
- Turn "Live Context" on in the "Set Context" setting
- Feel free to enable Live Context by default or not
- Send a message, either custom or suggested message
- Click the Enable Workstream Pattern Engine button in the system message response
- The permissions dialog will appear
- Enable the permissions from top to bottom
- Wait for the Desktop App to refresh
- The permissions dialog will re-appear and refresh itself, which should automatically turn the WPE on if the permissions were granted successfully

Can re-record any if needed! Lmk!

**Comment by tsavo-at-pieces** [comment]
Looks great for starters - @landon-at-pieces if you could do some holds / zooms i.e. kinda following the cursor around and making sure everything has time to be consumed that would be great! 

Other thing we might need to do is show a keyboard shortcut as a visible subtitle/title slide right before mack launches the power menu. 

I.e. "Get started by navigating to settings via the Command Pallet (CMD+SHIFT+P on macOS)" 

In the command pallet type "Go To Settings" etc..

**Comment by landon-at-pieces** [comment]
Here we go.

What do we think about this one: https://drive.google.com/file/d/1YsPTdtDxGR4yIwzl20biFrCM5-q_HE_T/view?usp=drive_link

**Comment by mack-at-pieces** [comment]
This is litttt @landon-at-pieces . @tsavo-at-pieces how's the pace for you? I kinda like the upbeat nature of it. Ppl can pause it as they see fit.

**Comment by tsavo-at-pieces** [comment]
Excellent!

**Comment by tsavo-at-pieces** [comment]
Let's get it on YouTube!

**Comment by mason-at-pieces** [comment]
@tsavo-at-pieces The only thing on the docs end is that the file is large so we'd have to embed the yt video for this one however the other videos are not yt embeds.

@landon-at-pieces Is there any way we can get a shorter version of this for the docs?

**Comment by landon-at-pieces** [comment]
Good deal. Will get this up.

**Comment by landon-at-pieces** [comment]
@mason-at-pieces -- What's the max file size you can embed?

**Comment by mason-at-pieces** [comment]
An example of one up is at 25mb but ideally they are under 10mb. Mainly just didn't want to upload a 300mb file into the docs repo haha, so any compression is good

**Comment by landon-at-pieces** [comment]
Do you still want the music cut? or just a compressed no audio version?

**Comment by tsavo-at-pieces** [comment]
Can we embed the youtube video?


*Tsavo Knott*
Co-Founder & CEO <https://www.linkedin.com/in/tsavoknott/>
@pieces.app <https://code.pieces.app/>

**Comment by mason-at-pieces** [comment]
> Can we embed the youtube video?

We can but it'll be the only embedded yt video on the page while all the others are mp4/webm

**Comment by tsavo-at-pieces** [comment]
Okay that's probably fine - for performance reasons is it better to embed a
youtube video or are the mp4's streamed?

Other thing about embedding YT videos where we can is they get views and we
have analytics on em.

*Tsavo Knott*
Co-Founder & CEO <https://www.linkedin.com/in/tsavoknott/>
@pieces.app <https://code.pieces.app/>

**Comment by mason-at-pieces** [comment]
> for performance reasons is it better to embed a youtube video or are the mp4's streamed?

As far as performance goes, Id assume the embed is better because it prob just renders a thumbnail and then streams in the video once a user clicks on it to play rather than the whole video being rendered at runtime.

> Other thing about embedding YT videos where we can is they get views and we have analytics on em.

I actually think yt counts embed views differently or are just way more strict but with the embed it could lead to users going to our youtube which is a plus.

My only thing is that this video seems to be in between our youtube style videos and our gif style videos so it just isn't clear on where it should go.

**Comment by landon-at-pieces** [comment]
Here's live YT link: https://www.youtube.com/watch?v=-zdK1bX0W-Y

Also here's a compressed (audioless) file if you want to embed: https://drive.google.com/file/d/1YTRCQ6RZoN0JPZeqOuJEQm4VAMsHPmvh/view?usp=drive_link

**Comment by tsavo-at-pieces** [comment]
Im game for either or! Maybe if we have youtube videos we use them and if
not we use the raw videos from here on out?

*Tsavo Knott*
Co-Founder & CEO <https://www.linkedin.com/in/tsavoknott/>
@pieces.app <https://code.pieces.app/>
