### ISSUE TITLE
Providing a flatpak build

### ISSUE THREAD

**Issue by Sherwin-14** [pieces-app/documentation#433]
Snaps are not used by many distributions except Ubuntu itself. Currently flatpaks are preferred over snaps by every distribution.

**Comment by mack-at-pieces** [comment]
Hi @Sherwin-14 - Thanks so much for the feedback. 

This repository is for issues and maintenance for the Pieces for Developers Documentation website (https://docs.pieces.app)

We have a public discussion around this over on our Support repository here: https://github.com/pieces-app/support/discussions/14 - do you mind sharing your thoughts there or creating a new GH issue within that repository? 

Thanks!
