### ISSUE TITLE
Obsidian Docs Page

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#44]
# Overview

Building docs page for Obsidian

## Features

- [ ] Onboarding to Pieces OS
- [ ] Save a Snippet
- [ ] Manage Your Snippets
- [ ] Insert Your Code Snippets
- [ ] Share Your Code Snippets

## Upcoming Features
- [ ] Embedded Functionality for Transforms (Formatting, Optimization, Boilerplate, etc.)
- [ ] Suggested Snippets
- [ ] Advanced Filtering Options
- [ ] Edit Your Snippets

**Comment by jordan-pieces** [comment]
@mason-at-pieces are there any updates here? Do these docs need upgraded? 

There are a few approaches that we can take - just need to know what you all would like to do. 
If you get me setup with the application in obsidian i can test these features and help with the docs. Or you can write out the initial versions and then let me know when I can come in and upgrade and make sure its good to go. 

I converted these to checkboxes so you can mark off which sections you are completed with for tracking here on this issue. 
Let me know!

**Comment by mason-at-pieces** [comment]
@jordan-pieces I can get you set up with Obsidian today after all hands if that works, shouldn't take too long.

I think the best route is to keep the overall format similar for all the products so it's super easy for users. If there is a format that we already have and like, then we can just use that and customize it to fit the features and quirks of Obsidian

**Comment by jordan-pieces** [comment]
Awesome my advice here is just to use the teams page on docs as a template - it is the best one right now @mason-at-pieces @randy-at-pieces
