### ISSUE TITLE
VS Code Videos to YT Videos

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#442]
@landon-at-pieces Here are the videos that need to be uploaded to YT as unlisted videos and you can add them all to a documentation playlist.

I've also added a bit of a description (title/text) that the video will support in the docs.

Ill go through the playlist and get the videos added to the docs site after they are all uploaded 👍 

---

## VS Code Videos

- [x] View Snippet In Markdown

If you'd like to get a closer look at a snippet before adding it to your project, click on the snippet in the list view and it will open in a Markdown preview. You'll be able to see the snippet and its context, including any tags, descriptions, titles, related links, related people, and previously generated shareable links.

https://github.com/pieces-app/documentation/assets/123421085/83f67b27-ab7d-41b3-bdae-64dfb7a9fa75

- [x] Edit Snippet

Editing a snippet that is saved to Pieces for Developers from VS Code is easy! To edit a snippet, follow these steps:

1. Open the Pieces Explorer using the activity bar
2. From the “Saved Pieces” drop down list, right-click on the snippet you want to change
3. Click "Edit"
4. Edit your snippet, then save by pressing ```CTRL + S``` or ```⌘ + S```

https://github.com/pieces-app/documentation/assets/123421085/13f5c5bc-f79e-4578-bd59-88ff13268f99

- [x] Save Snippets

To save code to Pieces from VS Code, simply highlight the snippet and save with:
1. Keyboard Shortcut
    - Windows: ```Shift + CTRL + V```
    - macOS: ```Shift + CMD + V```
2. Right Click
    - Right-click and select "Save to Pieces"

https://github.com/pieces-app/documentation/assets/123421085/8eb9171c-c992-4208-a024-e723a21c4ee2

- [x] Search for Snippets

To search for a snippet:

1. Open an editable file in VS Code
2. Right-click and choose "Search Pieces" or use the shortcut ```CTRL + ALT + P``` or ```⌘ + ⌥ + P```
3. Type keywords into the search bar, and when you hit enter, the snippet will be inserted into the file

https://github.com/pieces-app/documentation/assets/123421085/1e0d376b-b02b-4a27-9958-b8f1b462ced6

- [x] Ask Copilot
Ask the Copilot about a file, folder, snippet, code fragment, or terminal output. All available by right-clicking, and then selecting 'Ask Copilot'.

https://github.com/pieces-app/documentation/assets/123421085/90b207d0-2ea4-44ee-979b-3e3e55c3ecff

## JetBrains Videos

- [x] Related Materials

Related materials are code snippets that are similar to the code you're currently working on. Pieces is capable of identifying related code snippets, even if you're interested in code that isn't originally part of the Pieces snippet. To find related materials:

1. Highlight a code snippet in your editor
2. Right-click and select “Find Related Materials in Pieces”
3. Click the “View Insights” success message in the lower right corner of your editor to open the related materials in the Side Panel so that you can easily add them to your project.

https://github.com/pieces-app/documentation/assets/123421085/c319c5e2-365a-479a-a0b0-4e1f37f6830f

- [x] Suggested Snippets

Pieces offers you relevant code snippets based on your current activities and saved snippets. To access the suggested snippets, open the Pieces plugin and click on the dropdown menu labeled `Suggested snippets`. Here, you will be presented with a selection of code snippets that are closely aligned with your ongoing JetBrains workflow. The more you utilize the suggested code snippets, the more accurate and relevant they become to your coding style and the workflow.

https://github.com/pieces-app/documentation/assets/123421085/21296774-289f-435b-95c5-21a20c38a3f1

## Obsidian Videos

- [x] Embedded Buttons

Pieces adds **embedded buttons** into your markdown files to help you save, copy, enrich, & share your code snippets.

- **Save**: This button saves any code snippet to Pieces, so that you can easily refer to it later across the Pieces ecosystem.

- **Copy**: This button allows you to quickly copy your code to your clipboard.

- **Enrich**: This button generates helpful metadata and contextual information for your code and automatically adds it to the markdown surrounding your code block.

- **Share**: This button allows you to quickly share any code snippet with a link, for easy collaboration.

https://github.com/pieces-app/documentation/assets/123421085/03c27d6e-26c5-42af-a84a-1515ea25711e

- [x] Filtering Snippet List

To create a filter and show snippets based on a set of parameters, you can manually add filter settings to your snippet list. To add a filter based on tags, titles, content, and more:

1. Click on the filter button
2. Click “Add Filters” to see your filtering options
3. Select a filter
4. Fill out the inputs for what you would like to filter for
5. Click “Run Filters”

https://github.com/pieces-app/documentation/assets/123421085/36598a51-6d4d-428b-915f-2bc4f0045a57

- [x] Find Your Snippets

Click on the Pieces icon in the ribbon menu to open the Pieces view.
Using the sort by dropdown menu, sort your snippets by **recent** or by **language**.
Using the search box at the top of the view, search your snippets to save time leafing through your markdown files.

https://github.com/pieces-app/documentation/assets/123421085/ced6de13-41f1-4b75-8dd2-516842740356

- [x] Save Your Snippets

**To save a Snippet:**

- Highlight some text, right-click, and select "Save to Pieces."
- Click the Pieces button within any code block.
- Highlight the desired code and use a dedicated keyboard shortcut.

https://github.com/pieces-app/documentation/assets/123421085/5d47ec28-725f-42d0-be20-e354e47b4e83

- [x] Shareable Link

**To share a snippet:**

- Highlight the text, right-click, and select "Share via Pieces Link."
- Click the Pieces Share button within any code block/in the Pieces View.
- Highlight the desired code and use a dedicated keyboard shortcut.

https://github.com/pieces-app/documentation/assets/123421085/5d4d81ef-d14f-4c27-8a2f-efde7e022779

- [x] Use Your Snippets

- Click on 'view code' to view your snippets with syntax highlighting.
- Use the copy and share buttons on each of your snippets in the Pieces View.
- You can expand your code snippets to view automatically generated metadata.

https://github.com/pieces-app/documentation/assets/123421085/d1aa6db2-0b38-44a1-9e2c-f9aa6454f18a

**Comment by landon-at-pieces** [comment]
These should all be good to go. Links are in YouTube studio (I can provide those if you need them here).
