### ISSUE TITLE
PyCharm Plugin window text stays large regardless of window size.

### ISSUE THREAD

**Issue by cf-home** [pieces-app/documentation#453]
The text in the copilot plugin window is large.  When I resize the window, text gets cutoff rather than resized.

![Screenshot 2024-06-02 at 7 17 02 AM](https://github.com/pieces-app/documentation/assets/160560521/6cb4b649-f07e-4113-ab70-46e69ac5ce54)

**Comment by mason-at-pieces** [comment]
Hey @cf-home, this repo is actually just for issues around our documentation site. If you could create an issue on our [GitHub Support Repo](https://github.com/pieces-app/support/issues), our team can help figure out what's going on. Thanks!

I will close this issue.
