### ISSUE TITLE
301 redirect past AMA LP URL

### ISSUE THREAD

**Issue by cole-at-pieces** [pieces-app/documentation#456]
Change https://docs.pieces.app/ama/building-a-more-extensible-development-environment to https://docs.pieces.app/community/events/building-a-more-extensible-development-environment-ama and 301 redirect

**Comment by cole-at-pieces** [comment]
@mason-at-pieces could you also plz remove the registration links to the typeform on this LP? We're getting new submissions still.

**Comment by mason-at-pieces** [comment]
@cole-at-pieces Going to assume the `-ama` at the end of the redirect was a typo?
