### ISSUE TITLE
Update links to Privacy and Security

### ISSUE THREAD

**Issue by cole-at-pieces** [pieces-app/documentation#512]
<img width="247" alt="Screenshot 2024-08-05 at 11 12 58 AM" src="https://github.com/user-attachments/assets/bc4740e9-0c25-4243-9555-593192aca6b6">

Change links to Privacy Policy and Terms of Service to:
https://pieces.app/legal/privacy-policy
https://pieces.app/legal/terms

Then delete these docs pages and 301 redirect to the pieces.app links mentioned above:
https://docs.pieces.app/privacy-policy
https://docs.pieces.app/terms

**Comment by cole-at-pieces** [comment]
this is in the footer of the docs

**Comment by cole-at-pieces** [comment]
@mason-at-pieces the goal was not to delete the links-keeping this open

**Comment by mason-at-pieces** [comment]
Added them back 👍  closing again haha
