### ISSUE TITLE
Add Linux Update Instructions to Docs

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#56]
# Overview

There's been a couple of people on Discord have issues with updating Pieces on Linux. I think just include the following on Linux page would be very helpful.

[Link to related Discord post](https://discord.com/channels/1098986658851999776/1117790404499210360)

## Add something similar to the docs page

Update individual snap packages:

`sudo snap refresh pieces-for-developers`

`sudo snap refresh pieces-os`

### OR

Update all snap packages:

`sudo snap refresh`

**Comment by jordan-pieces** [comment]
@mason-at-pieces added this section to linux install page, super basic for now :) 

<img width="970" alt="Screenshot 2023-06-15 at 10 34 04 AM" src="https://github.com/pieces-app/documentation/assets/55861512/331e1abe-ccac-4da1-bc00-ae11d672d281">

**Comment by mason-at-pieces** [comment]
Sick
