### ISSUE TITLE
Add Discord and Typeform Link (Support TF) to Sidebar

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/documentation#61]
- [ ] Add buttons to sidebar for:
    - [ ] Support Typeform 
    - [ ] Joining Discord Link
- [ ] (optional) Add icons if needed 

@mason-at-pieces would be great to know if there is a specific link i should be using here or if i can just use the generic support link

**Comment by tsavo-at-pieces** [comment]
Here is the support link: https://getpieces.typeform.com/to/mCjBSIjF

Discord Link I think is just discord.gg/getpieces

**Comment by mason-at-pieces** [comment]
@jordan-pieces @tsavo-at-pieces For the docs sidebar, I'd say just use `discord.gg/getpieces` 👍 

Also, if we could get `pieces.app/discord` set up to redirect to the above invite that would be 🔥

**Comment by jordan-pieces** [comment]
@tsavo-at-pieces do you know where the pieces.app domain is hosted currently? wherever that is is where we need to setup the redirect for that route to push to the discord.gg/getpieces link - we can also take care of this when we have the site all on pieces.app

lmk
