### ISSUE TITLE
Update Obsidian Plugin Install Instructions

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#63]
Installation instructions for the Obsidian plugin have been updated.

You can literally just copy this section here: https://github.com/pieces-app/obsidian-pieces#install-instructions

**Comment by jordan-pieces** [comment]
@mason-at-pieces can you check this here for me and let me know if this is tale or if this requires any further changes?

**Comment by mason-at-pieces** [comment]
Yep, I think that's all good

**Comment by jordan-pieces** [comment]
ill double check again before these updates just in case! :) but thank you!
