### ISSUE TITLE
Obsidian Link Update

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#64]
We changed our Obsidian plugin ID resulting in the link needing to be updated. Applies to anywhere the old link is.

From: `https://obsidian.md/plugins?id=obsidian-pieces`

To: `https://obsidian.md/plugins?id=pieces-for-developers`

**Comment by jordan-pieces** [comment]
This has already been updated (i believe by you @mason-at-pieces). also for you and anyone else that sees this issue: 

Most links are actually controlled from the docs.json so anything that needs updated likely lives there. :)
