### ISSUE TITLE
Updated Plugins Sections

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#65]
# Overview

Moving our plugins section on the home page to be under the `Download Pieces for Developers Desktop App` section.

Also changes the title of the section to `Use with your favorite tools`

<img width="796" alt="Screenshot 2023-06-16 at 11 16 56 AM" src="https://github.com/pieces-app/plugin_obsidian/assets/123421085/a6ad99c0-3791-4fb4-9d54-4dc63363cd55">

**Comment by jordan-pieces** [comment]
I went ahead and did this: 

![Screenshot 2023-06-26 at 4 20 43 PM](https://github.com/pieces-app/documentation/assets/55861512/a311560f-ec0b-4892-8493-f3884a9d8de2)

so now the starting points are moved up and then also the plugins, and the gif is barely there to help encourage them to scroll

Its on a larger PR but it should be linked to the development section above

**Comment by mason-at-pieces** [comment]
2 Notes:
- We need to add JupyterLab logo in, if not already done
- Are we keeping the Desktop App in that list?
- I forget what we were talking about renaming the `Try all of our products` to, maybe it was `Get our other products`? I just think `Try` might not be exactly what we want to say

**Comment by jordan-pieces** [comment]
![Screenshot 2023-06-27 at 3 39 12 PM](https://github.com/pieces-app/documentation/assets/55861512/692e303a-969f-4f19-9828-aebdddff9a3d)

**Comment by mason-at-pieces** [comment]
Yes, beautiful
