### ISSUE TITLE
VSCode extension hijacks default key bindings

### ISSUE THREAD

**Issue by kb-ig** [pieces-app/documentation#69]
Having just installed the VSCode extension for pieces, I notice that the key mapping to "Search pieces" is `Ctrl + k`. This is a common key mapping for various features in VSCode (`Ctrl + k + c`, to comment out code, `Ctrl + k + w` to close all tabs), and installing this extension means I can no longer use these default key bindings.

I cant see any way to override your key bindings - is it at all possible? If not, I think it's something that should be considered. 

[This is a list](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf) of the VSCode key bindings, and below highlights the ones that use `Ctrl + k`, which no longer work while this extension is installed.
![image](https://github.com/pieces-app/documentation/assets/91877080/b77e4493-ec85-447f-aaef-7e40c6bd4934)

**Comment by kb-ig** [comment]
Apologies if this is the wrong repo to raise issues on. It's the one linked in the VSCode extension page.

**Comment by jordan-pieces** [comment]
@kb-ig this is totally fine, feel free to open up issues here if you have other questions. But I understand this issue here, let me circulate this around internally and have some conversations about improving this experience. Just out of curiosity, if you could pick a default key bind for Pieces Search, what would you select?

Thanks for bringing this up, and feel free to join the discord and we can stay in touch! Otherwise i will follow up with you here once those conversations happen. 

Here is the link for the discord: [https://discord.gg/XGRPRfzj](https://discord.gg/XGRPRfzj)

**Comment by jordan-pieces** [comment]
@kb-ig This is actively being worked on by @kuba-pieces this week and should be resolved soon!

**Comment by kb-ig** [comment]
Great stuff, thanks for the update @jordan-pieces.

To answer your earlier question around which key binding I'd pick; that's a tough one, and you can guarantee that whatever I'd pick would interfere with someone else's work flow. I think the important thing is to have it configurable so each user can change it based on how they work. Additionally, I think it would be good to remove the key binding so the only way to search pieces is by using the command palette. 

Maybe `Ctrl + Alt + P` could be a good candidate. For me, it's currently used by one other extension (SVG Preview) but this only applies when an SVG file is open in the editor.

**Comment by kuba-pieces** [comment]
@kb-ig I'm happy to let you know that 0.6.4 went live on Tuesday and it has the exact shortcut you mentioned assigned to search functionality :) Let us know if it solves the problem

**Comment by jordan-pieces** [comment]
@kb-ig @kuba-pieces i am going to close this ticket - but feel free to open or comment again if needed in the future. :)

**Comment by kb-ig** [comment]
Thanks both, I can confirm this update fixes the issue :grinning:
