### ISSUE TITLE
Broken Pieces OS Install Link

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/documentation#70]
On [this page](https://docs.pieces.app/extensions-plugins/vscode), the Pieces OS link in the video is broken.

https://github.com/pieces-app/documentation/assets/123421085/8f0e320c-11cc-4594-87a6-f43762726d17

**Comment by jordan-pieces** [comment]
@mason-at-pieces this has been patched on a recent merge into main :) may require a refresh but should be updated
