### ISSUE TITLE
Document more of our Features

### ISSUE THREAD

**Issue by georgia-at-pieces** [pieces-app/documentation#72]
**PFD**
- [x] Copilot https://docs.pieces.app/~74/features/pieces-copilot 
- [x] Snippet-specific copilot https://docs.pieces.app/~74/features/pieces-copilot#snippet-specific-copilot
- [x] Duplicating a snippet https://docs.pieces.app/~74/features/managing-saved-materials#duplicating-a-code-snippet
- [x] Transforms
- [x] Collections
- [x] Global Search https://docs.pieces.app/~74/features/global-search
- [x] Settings (explain all) https://docs.pieces.app/~74/features/user-settings
- [x] How to Update on mac/Windows/Linux https://docs.pieces.app/~74/features/user-settings#check-for-updates
- [ ] Troubleshooting common install problems
- [ ] Uninstalling - Added macOS and Windows; not Linux
- [x] Keyboard shortcuts https://docs.pieces.app/~74/features/keyboard-shortcuts
- [x] In-app notifications critical v non-critical https://docs.pieces.app/~74/features/user-settings#in-app-notifications
- [x] Filtering workflow activity https://docs.pieces.app/~74/features/workflow-activity#workflow-activity-search--filters
- [x] Change password
- [x] Creating a cloud/account does not sync snippets between devices

**VS Code**
- [ ] Suggested materials
- [ ] Explored materials
- [ ] Related materials
- [ ] Connect account
- [ ] Updating
- [ ] Troubleshooting common install problems
- [ ] Uninstalling
- [ ] Settings

**JetBrains**
- [ ] Suggested materials
- [ ] Explored materials
- [ ] Related materials
- [ ] Updating
- [ ] Troubleshooting common install problems
- [ ] Uninstalling
- [ ] Settings

**Web Extensions**
- [ ] Recently discovered snippets
- [ ] Discovered snippets
- [ ] Settings
- [ ] Updating
- [ ] Troubleshooting install problems
- [ ] Uninstalling
- [ ] Get shareable links to open when using Brave

**Obsidian** 

**Jupyter**

**Comment by jordan-pieces** [comment]
@georgia-at-pieces i changed my mind im going to actually set this up to be separate issues for each plugin with the list for what is needed
