### ISSUE TITLE
Add App Screenshots to New Documentation Pages

### ISSUE THREAD

**Issue by mack-at-pieces** [pieces-app/documentation#88]
We can definitely add app screenshots to some of the new pages to better highlight what the documentation is talking about

- [x] Collections
- [x] User Settings
- [x] Global Copilot
- [x] Contextual Copilot

**Comment by jordan-pieces** [comment]
@laurin-at-pieces when you have time today can you link me to some of these assets and any content they already have that exist out there?

**Comment by jordan-pieces** [comment]
this has been resolved via linked PR
